# http://docs.travis-ci.com/user/languages/r/
language: r

cache: packages

r:
  - release

r_github_packages:
  - r-dbi/RPostgres@v0.1-8

after_success:
  - Rscript -e 'covr::coveralls(function_exclusions = c("\\.onLoad"))'

warnings_are_errors: false
  
notifications:
  email:
    - zozlak@zozlak.org
